# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rendumonnaiedynamique.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import pygame
pygame.mixer.init()
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        icon = QtGui.QIcon("image/icone.ico")
        MainWindow.setWindowIcon(icon)
        
##LABEL PRIX
        self.labelprix = QtWidgets.QLabel(self.centralwidget)
        self.labelprix.setGeometry(QtCore.QRect(50, 0, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.labelprix.setFont(font)
        self.labelprix.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelprix.setObjectName("labelprix")

##BOUTON1
        self.BOUTON1 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON1.setGeometry(QtCore.QRect(20, 70, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON1.setFont(font)
        self.BOUTON1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON1.setObjectName("BOUTON1")
        self.BOUTON1.clicked.connect(self.bouton1)

##BOUTON2
        self.BOUTON2 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON2.setGeometry(QtCore.QRect(100, 70, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON2.setFont(font)
        self.BOUTON2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON2.setObjectName("BOUTON2")
        self.BOUTON2.clicked.connect(self.bouton2)

##BOUTON3
        self.BOUTON3 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON3.setGeometry(QtCore.QRect(180, 70, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON3.setFont(font)
        self.BOUTON3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON3.setObjectName("BOUTON3")
        self.BOUTON3.clicked.connect(self.bouton3)

##BOUTON4
        self.BOUTON4 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON4.setGeometry(QtCore.QRect(20, 140, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON4.setFont(font)
        self.BOUTON4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON4.setObjectName("BOUTON4")
        self.BOUTON4.clicked.connect(self.bouton4)
#BOUTON5
        self.BOUTON5 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON5.setGeometry(QtCore.QRect(100, 140, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON5.setFont(font)
        self.BOUTON5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON5.setObjectName("BOUTON5")
        self.BOUTON5.clicked.connect(self.bouton5)
        
#BOUTON6
        self.BOUTON6 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON6.setGeometry(QtCore.QRect(180, 140, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON6.setFont(font)
        self.BOUTON6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON6.setObjectName("BOUTON6")
        self.BOUTON6.clicked.connect(self.bouton6)
        
##BOUTON7
        self.BOUTON7 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON7.setGeometry(QtCore.QRect(20, 210, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON7.setFont(font)
        self.BOUTON7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON7.setObjectName("BOUTON7")
        self.BOUTON7.clicked.connect(self.bouton7)

##deuxieme partie du Boutton droit mais quand je le deplace le code fonctionne plus ^^
##du coup il reste là
        self.BOUTONDROIT = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTONDROIT.setGeometry(QtCore.QRect(20, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(12)

##BOUTON8
        self.BOUTON8 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON8.setGeometry(QtCore.QRect(100, 210, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON8.setFont(font)
        self.BOUTON8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON8.setObjectName("BOUTON8")
        self.BOUTON8.clicked.connect(self.bouton8)
        
##BOUTON9
        self.BOUTON9 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON9.setGeometry(QtCore.QRect(180, 210, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON9.setFont(font)
        self.BOUTON9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON9.setObjectName("BOUTON9")
        self.BOUTON9.clicked.connect(self.bouton9)
        
##BOUTON0
        self.BOUTON0 = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTON0.setGeometry(QtCore.QRect(100, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTON0.setFont(font)
        self.BOUTON0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTON0.setObjectName("BOUTON0")
        self.BOUTON0.clicked.connect(self.bouton0)
        
##premiere partie BOUTON DROIT
        self.BOUTONDROIT.setFont(font)
        self.BOUTONDROIT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTONDROIT.setObjectName("BOUTONDROIT")
        
##BOUTON RESET
        self.BOUTONRESET = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTONRESET.setGeometry(QtCore.QRect(180, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BOUTONRESET.setFont(font)
        self.BOUTONRESET.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTONRESET.setObjectName("BOUTONRESET")
        self.BOUTONRESET.clicked.connect(self.reset)
#somme perçue
        self.labelsommepercue = QtWidgets.QLabel(self.centralwidget)
        self.labelsommepercue.setGeometry(QtCore.QRect(70, 360, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.labelsommepercue.setFont(font)
        self.labelsommepercue.setObjectName("labelsommepercue")

##spinbox sommepercue 
        self.spinBoxsommepercue = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxsommepercue.setGeometry(QtCore.QRect(60, 390, 161, 22))
        self.spinBoxsommepercue.setMinimum(1)
        self.spinBoxsommepercue.setMaximum(1000)
        self.spinBoxsommepercue.setObjectName("spinBoxsommepercue")

##BOUTON ENCAISSER
        self.BOUTONENCAISSER = QtWidgets.QToolButton(self.centralwidget)
        self.BOUTONENCAISSER.setGeometry(QtCore.QRect(30, 420, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BOUTONENCAISSER.setFont(font)
        self.BOUTONENCAISSER.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOUTONENCAISSER.setObjectName("BOUTONENCAISSER")
        self.BOUTONENCAISSER.clicked.connect(self.encaisser)
##ligne de séparation
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(270, 0, 21, 481))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.arendre = QtWidgets.QLabel(self.centralwidget)
        self.arendre.setGeometry(QtCore.QRect(300, 0, 201, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        self.arendre.setFont(font)

##label à rendre
        self.arendre.setObjectName("arendre")
        self.euro = QtWidgets.QLabel(self.centralwidget)
        self.euro.setGeometry(QtCore.QRect(310, 50, 71, 61))
        self.euro.setText("")
        
##IMAGES DES PIECES ET BILLETS
        self.euro.setPixmap(QtGui.QPixmap("image/argent/1euro.png"))
        self.euro.setScaledContents(True)
        self.euro.setObjectName("euro")
        self.euro_2 = QtWidgets.QLabel(self.centralwidget)
        self.euro_2.setGeometry(QtCore.QRect(310, 130, 61, 61))
        self.euro_2.setText("")
        self.euro_2.setPixmap(QtGui.QPixmap("image/argent/2euro.png"))
        self.euro_2.setScaledContents(True)
        self.euro_2.setObjectName("euro_2")
        self.euro_3 = QtWidgets.QLabel(self.centralwidget)
        self.euro_3.setGeometry(QtCore.QRect(300, 210, 81, 61))
        self.euro_3.setText("")
        self.euro_3.setPixmap(QtGui.QPixmap("image/argent/5euro.png"))
        self.euro_3.setScaledContents(True)
        self.euro_3.setObjectName("euro_3")
        self.euro_4 = QtWidgets.QLabel(self.centralwidget)
        self.euro_4.setGeometry(QtCore.QRect(300, 300, 111, 61))
        self.euro_4.setText("")
        self.euro_4.setPixmap(QtGui.QPixmap("image/argent/10euro.png"))
        self.euro_4.setScaledContents(True)
        self.euro_4.setObjectName("euro_4")
        self.euro_6 = QtWidgets.QLabel(self.centralwidget)
        self.euro_6.setGeometry(QtCore.QRect(300, 390, 111, 61))
        self.euro_6.setText("")
        self.euro_6.setPixmap(QtGui.QPixmap("image/argent/20euro.png"))
        self.euro_6.setScaledContents(True)
        self.euro_6.setObjectName("euro_6")
        self.euro_7 = QtWidgets.QLabel(self.centralwidget)
        self.euro_7.setGeometry(QtCore.QRect(500, 50, 111, 61))
        self.euro_7.setText("")
        self.euro_7.setPixmap(QtGui.QPixmap("image/argent/50euro.png"))
        self.euro_7.setScaledContents(True)
        self.euro_7.setObjectName("euro_7")
        self.euro_8 = QtWidgets.QLabel(self.centralwidget)
        self.euro_8.setGeometry(QtCore.QRect(500, 130, 111, 61))
        self.euro_8.setText("")
        self.euro_8.setPixmap(QtGui.QPixmap("image/argent/100euro.png"))
        self.euro_8.setScaledContents(True)
        self.euro_8.setObjectName("euro_8")
        self.euro_9 = QtWidgets.QLabel(self.centralwidget)
        self.euro_9.setGeometry(QtCore.QRect(500, 210, 111, 61))
        self.euro_9.setText("")
        self.euro_9.setPixmap(QtGui.QPixmap("image/argent/200euro.png"))
        self.euro_9.setScaledContents(True)
        self.euro_9.setObjectName("euro_9")
        self.euro_10 = QtWidgets.QLabel(self.centralwidget)
        self.euro_10.setGeometry(QtCore.QRect(500, 300, 111, 61))
        self.euro_10.setText("")
        self.euro_10.setPixmap(QtGui.QPixmap("image/argent/500euro.png"))
        self.euro_10.setScaledContents(True)
        self.euro_10.setObjectName("euro_10")

##affichage du nombre de pieces de 1euro à donner
        self.nb_euro1 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro1.setGeometry(QtCore.QRect(390, 60, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro1.setFont(font)
        self.nb_euro1.setObjectName("nb_euro1")

##affichage du nombre de pieces de 2euro à donner
        self.nb_euro2 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro2.setGeometry(QtCore.QRect(390, 140, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro2.setFont(font)
        self.nb_euro2.setObjectName("nb_euro2")

##affichage du nombre de pieces de 5euros à donner
        self.nb_euro5 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro5.setGeometry(QtCore.QRect(390, 220, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro5.setFont(font)
        self.nb_euro5.setObjectName("nb_euro5")

##affichage du nombre de billets de 10euros à donner
        self.nb_euro10 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro10.setGeometry(QtCore.QRect(420, 310, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro10.setFont(font)
        self.nb_euro10.setObjectName("nb_euro10")

##affichage du nombre de billets de 20euros à donner
        self.nb_euro20 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro20.setGeometry(QtCore.QRect(420, 400, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro20.setFont(font)
        self.nb_euro20.setObjectName("nb_euro20")

##affichage du nombre de billets de 50euros à donner
        self.nb_euro50 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro50.setGeometry(QtCore.QRect(620, 60, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro50.setFont(font)
        self.nb_euro50.setObjectName("nb_euro50")

##affichage du nombre de billets de 100euros à donner
        self.nb_euro100 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro100.setGeometry(QtCore.QRect(620, 140, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro100.setFont(font)
        self.nb_euro100.setObjectName("nb_euro100")

##affichage du nombre de billets de 200euros à donner
        self.nb_euro200 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro200.setGeometry(QtCore.QRect(620, 220, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro200.setFont(font)
        self.nb_euro200.setObjectName("nb_euro200")

##affichage du nombre de billets de 500euros à donner
        self.nb_euro500 = QtWidgets.QLabel(self.centralwidget)
        self.nb_euro500.setGeometry(QtCore.QRect(620, 310, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.nb_euro500.setFont(font)
        self.nb_euro500.setObjectName("nb_euro500")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.PRIX = ""
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RenduMonnaie"))
        self.BOUTON1.setText(_translate("MainWindow", "1"))
        self.labelprix.setText(_translate("MainWindow", ""))
        self.BOUTON2.setText(_translate("MainWindow", "2"))
        self.BOUTON3.setText(_translate("MainWindow", "3"))
        self.BOUTON4.setText(_translate("MainWindow", "4"))
        self.BOUTON5.setText(_translate("MainWindow", "5"))
        self.BOUTON6.setText(_translate("MainWindow", "6"))
        self.BOUTON7.setText(_translate("MainWindow", "7"))
        self.BOUTONDROIT.setText(_translate("MainWindow", "DROIT"))
        self.BOUTON8.setText(_translate("MainWindow", "8"))
        self.BOUTON9.setText(_translate("MainWindow", "9"))
        self.BOUTON0.setText(_translate("MainWindow", "0"))
        self.labelsommepercue.setText(_translate("MainWindow", "somme perçue :"))
        self.BOUTONENCAISSER.setText(_translate("MainWindow", "ENCAISSER"))
        self.BOUTONRESET.setText(_translate("MainWindow", "RESET"))
        self.arendre.setText(_translate("MainWindow", "à rendre :"))
        self.nb_euro1.setText(_translate("MainWindow", ""))
        self.nb_euro2.setText(_translate("MainWindow", ""))
        self.nb_euro5.setText(_translate("MainWindow", ""))
        self.nb_euro10.setText(_translate("MainWindow", ""))
        self.nb_euro20.setText(_translate("MainWindow", ""))
        self.nb_euro50.setText(_translate("MainWindow", ""))
        self.nb_euro100.setText(_translate("MainWindow", ""))
        self.nb_euro200.setText(_translate("MainWindow", ""))
        self.nb_euro500.setText(_translate("MainWindow", ""))

##Code rendu de monanie dynamique
    def RM_BU(self,L, X):
        n = len(L)
        Stock = [0] * (X + 1)
        Garde = [0] * (X + 1)
        for j in range(1, X + 1):
            Mini = j + 1
            for i in range(n):
                if L[i] <= j:
                    Nb = 1 + Stock[j - L[i]]
                    if Nb < Mini:
                        Mini = Nb
                        Garde[j] = i + 1
            Stock[j] = Mini
        x, P = X, []
        while x > 0:
            P.append(L[Garde[x] - 1])
            x -= L[Garde[x] - 1]
        return Stock[X], P

##Affichage du prix en direct avec les boutons
    def bouton1(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "1"
        self.labelprix.setText(self.PRIX)
    def bouton2(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "2"
        self.labelprix.setText(self.PRIX)
    def bouton3(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "3"
        self.labelprix.setText(self.PRIX)
    def bouton4(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "4"
        self.labelprix.setText(self.PRIX)
    def bouton5(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "5"
        self.labelprix.setText(self.PRIX)
    def bouton6(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "6"
        self.labelprix.setText(self.PRIX)
    def bouton7(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "7"
        self.labelprix.setText(self.PRIX)
    def bouton8(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "8"
        self.labelprix.setText(self.PRIX)
    def bouton9(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "9"
        self.labelprix.setText(self.PRIX)
    def bouton0(self):
        pygame.mixer.music.load("sons/bip-bouton.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = self.PRIX + "0"
        self.labelprix.setText(self.PRIX)

##bouton reset pour reset le montant du prix
    def reset(self):
        pygame.mixer.music.load("sons/boutonreset.mp3")
        pygame.mixer.music.play(loops=0)
        self.PRIX = ""
        self.labelprix.setText(self.PRIX)
        self.nb_euro1.setText("")
        self.nb_euro2.setText("")
        self.nb_euro5.setText("")
        self.nb_euro10.setText("")
        self.nb_euro20.setText("")
        self.nb_euro50.setText("")
        self.nb_euro100.setText("")
        self.nb_euro200.setText("")
        self.nb_euro500.setText("")
        self.spinBoxsommepercue.setValue(1)
        
##distribution des données rendu par la fonction RM_BU pour l'affichage
    def distr(self, donnes):
    # Dictionnaire pour stocker le nombre de chaque type de billet/monnaie à rendre
        billets_a_rendre = {
            1: 0,
            2: 0,
            5: 0,
            10: 0,
            20: 0,
            50: 0,
            100: 0,
            200: 0,
            500: 0
        }
        for billet in donnes[1]:
            billets_a_rendre[billet] += 1
        self.nb_euro1.setText("X" + str(billets_a_rendre[1]) if billets_a_rendre[1] > 0 else "")
        self.nb_euro2.setText("X" + str(billets_a_rendre[2]) if billets_a_rendre[2] > 0 else "")
        self.nb_euro5.setText("X" + str(billets_a_rendre[5]) if billets_a_rendre[5] > 0 else "")
        self.nb_euro10.setText("X" + str(billets_a_rendre[10]) if billets_a_rendre[10] > 0 else "")
        self.nb_euro20.setText("X" + str(billets_a_rendre[20]) if billets_a_rendre[20] > 0 else "")
        self.nb_euro50.setText("X" + str(billets_a_rendre[50]) if billets_a_rendre[50] > 0 else "")
        self.nb_euro100.setText("X" + str(billets_a_rendre[100]) if billets_a_rendre[100] > 0 else "")
        self.nb_euro200.setText("X" + str(billets_a_rendre[200]) if billets_a_rendre[200] > 0 else "")
        self.nb_euro500.setText("X" + str(billets_a_rendre[500]) if billets_a_rendre[500] > 0 else "")


##bouton encaisser pour afficher
    def encaisser(self):
        if int(self.PRIX) >=1000:
            self.spinBoxsommepercue.setValue(1)
            self.PRIX = ""
            self.labelprix.setText(self.PRIX)
            QMessageBox.warning(self.centralwidget, "Avertissement", "Il est interdit de payer en especes pour les payements supérieurs ou égaux à 1000euros")
        elif int(self.PRIX) > self.spinBoxsommepercue.value():
            self.spinBoxsommepercue.setValue(1)
            self.PRIX = ""
            self.labelprix.setText(self.PRIX)
            QMessageBox.warning(self.centralwidget, "Avertissement", "Vous n'avez pas assez d'argent !")
        else:
            pygame.mixer.music.load("sons/encaissement.mp3")
            pygame.mixer.music.play(loops=0)
            self.distr(self.RM_BU([1, 2, 5, 10, 20, 50, 100, 200, 500],int(self.spinBoxsommepercue.value()-int(self.PRIX))))
            self.spinBoxsommepercue.setValue(1)
            self.PRIX = ""
            self.labelprix.setText(self.PRIX)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
